#!/usr/bin/env python3
"""Keep the inventory in ``docs/README.md`` (the map) equal to the tree.

The map has two parts. The hand-written part says, per KIND of information,
which ONE file is its home, how that file is kept current, and when to read
it. The generated part, between the two marker comments below, lists every
TRACKED top-level ``docs/*.md`` with its title and every ``docs/<folder>/``
holding a tracked file, with the folder's index file. This script writes
that part and, with ``--check``, refuses when it no longer matches the tree.

Why generated: on 2026-09-30, 268 of 538 tracked ``.md`` files were not
reachable within three links of ``AGENTS.md``
(``scripts/measure_doc_reachability.py``). A hand-kept list decays the same
way the ADR index did twice (``scripts/generate_adr_index.py``); a generated
list checked in ``make validate`` cannot.

What turns ``--check`` red: adding, deleting or renaming a tracked top-level
``docs/*.md`` or a ``docs/<folder>/``; changing a top-level file's first
``# `` heading; adding or removing a folder's index file (``README.md``,
``00-index.md``, ``00-study-index.md``, ``INDEX.md``). Fix:
``git add`` the file, then ``python3 scripts/check_docs_map.py``.

Enumeration is ``git ls-files``, not the filesystem, so an untracked scratch
file or an editor's hidden folder under ``docs/`` cannot make a correct
committed tree red (the trap AGENTS.md rule 13a records for another gate).
The price: a NEW doc is invisible to this gate until it is ``git add``ed —
the same trade ``tests/unit/test_docs_numbering_no_collisions.py`` made.

What it cannot see: whether the hand-written part names the RIGHT home for a
kind of information, or whether a file inside a folder is worth reading.

``DOCS_MAP_ROOT`` (an environment variable) points the script at another
repository root; the tests use it to drive ``make docs-map-check`` against a
throwaway tree.
"""

from __future__ import annotations

import argparse
import difflib
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BEGIN = "<!-- docs-map:begin (generated by scripts/check_docs_map.py; do not edit by hand) -->"
END = "<!-- docs-map:end -->"

#: A folder's index is the first of these that exists in it. ``docs/adr/`` is
#: the exception: its index is ``docs/24-adr-index.md``, generated and checked
#: by ``scripts/generate_adr_index.py``.
_INDEX_NAMES = ("README.md", "00-index.md", "00-study-index.md", "INDEX.md")
_SPECIAL_INDEX = {
    "adr": "../24-adr-index.md (generated)",
    "analysis": "00-index.md covers the 2026-07 plan only; the rest by date in the file name",
}


def _tracked(root: Path) -> list[str]:
    """Paths under ``docs/`` that git tracks, NUL-separated so a space in a
    name cannot split one file into two."""
    out = subprocess.run(
        ["git", "ls-files", "-z", "--", "docs"],
        capture_output=True,
        cwd=root,
        check=True,
    ).stdout
    return [p.decode("utf-8") for p in out.split(b"\0") if p]


def _title(path: Path) -> str:
    """The first ``# `` heading outside a code fence, or the file name."""
    in_fence = False
    for line in path.read_text(encoding="utf-8-sig", errors="replace").splitlines():
        if line.startswith(("```", "~~~")):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = re.match(r"^#\s+(.+?)\s*#*\s*$", line)
        if match:
            return match.group(1).replace("|", "\\|")
    return path.name


def _top_level_docs(root: Path) -> list[Path]:
    names = sorted(
        p.split("/", 1)[1]
        for p in _tracked(root)
        if p.count("/") == 1 and p.lower().endswith(".md")
    )
    return [root / "docs" / name for name in names]


def _folders(root: Path) -> list[Path]:
    names = sorted({p.split("/")[1] for p in _tracked(root) if p.count("/") >= 2})
    return [root / "docs" / name for name in names]


def _folder_index(folder: Path, tracked: set[str]) -> str:
    special = _SPECIAL_INDEX.get(folder.name)
    if special:
        return special
    for name in _INDEX_NAMES:
        if f"docs/{folder.name}/{name}" in tracked:
            return name
    return "none — read by file name and date"


def render_inventory(root: Path = ROOT) -> str:
    """The generated part, markers included."""
    tracked = set(_tracked(root))
    lines = [BEGIN, "", "### Every tracked top-level `.md` file in `docs/`", ""]
    lines.append("| File | Title |")
    lines.append("|---|---|")
    for path in _top_level_docs(root):
        lines.append(f"| `{path.name}` | {_title(path)} |")
    lines += ["", "### Every folder in `docs/`", ""]
    lines.append("| Folder | Index |")
    lines.append("|---|---|")
    for folder in _folders(root):
        lines.append(f"| `{folder.name}/` | {_folder_index(folder, tracked)} |")
    lines += ["", END]
    return "\n".join(lines) + "\n"


def _split(text: str, map_path: Path) -> tuple[str, str, str]:
    """(before, generated, after); raises SystemExit unless each marker
    appears exactly once, BEGIN before END. A second generated block would
    otherwise be ignored — and could carry a stale inventory unchecked."""
    if text.count(BEGIN) != 1 or text.count(END) != 1 or text.find(END) < text.find(BEGIN):
        raise SystemExit(
            f"{map_path}: the generated section needs exactly one {BEGIN!r} followed by "
            f"exactly one {END!r}"
        )
    start = text.find(BEGIN)
    end = text.find(END) + len(END) + 1  # include the newline after END
    return text[:start], text[start:end], text[end:]


def check(root: Path = ROOT, map_path: Path | None = None) -> int:
    """0 when the map's generated part equals the tree; 1 otherwise."""
    map_path = map_path or (root / "docs" / "README.md")
    if not map_path.is_file():
        print(f"ERROR: {map_path} is missing", file=sys.stderr)
        return 1
    _, current, _ = _split(map_path.read_text(encoding="utf-8"), map_path)
    files = _top_level_docs(root)
    # Floor: a gate that passes over nothing has measured nothing (AGENTS.md,
    # "Every gate must report what it counted"). A wrong root or a moved docs/
    # directory would otherwise agree trivially with an empty map.
    if not files:
        print(
            "ERROR: no tracked top-level docs/*.md found; refusing to pass over nothing",
            file=sys.stderr,
        )
        return 1
    expected = render_inventory(root)
    if current == expected:
        print(
            f"docs map current: {len(files)} top-level files, {len(_folders(root))} folders listed"
        )
        return 0
    print(
        "ERROR: docs/README.md's generated inventory is stale. Diff (map -> tree):", file=sys.stderr
    )
    for line in difflib.unified_diff(
        current.splitlines(), expected.splitlines(), "docs/README.md", "tree", lineterm=""
    ):
        print(line, file=sys.stderr)
    print("Fix: git add the new file, then python3 scripts/check_docs_map.py", file=sys.stderr)
    return 1


def write(root: Path = ROOT, map_path: Path | None = None) -> int:
    map_path = map_path or (root / "docs" / "README.md")
    before, _, after = _split(map_path.read_text(encoding="utf-8"), map_path)
    map_path.write_text(before + render_inventory(root) + after, encoding="utf-8")
    print(f"wrote the generated inventory into {map_path}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the inventory is stale")
    args = parser.parse_args(argv)
    root = Path(os.environ.get("DOCS_MAP_ROOT") or ROOT).resolve()
    return check(root) if args.check else write(root)


if __name__ == "__main__":
    raise SystemExit(main())
