#!/usr/bin/env python3
"""Keep the inventory in ``docs/README.md`` (the map) equal to the tree.

The map has two parts. The hand-written part says, per KIND of information,
which ONE file is its home, how that file is kept current, and when to read
it. The generated part, between the two marker comments below, lists every
top-level ``docs/*.md`` with its title and every ``docs/<folder>/`` with its
index file. Files INSIDE a folder are not counted, so adding one (a dated
handoff, an ADR) does not touch this file; adding a top-level file or a
folder does. This script writes that part and, with
``--check``, refuses when it no longer matches the tree.

Why generated: on 2026-09-30, 268 of 538 tracked ``.md`` files were not
reachable within three links of ``AGENTS.md``
(``scripts/measure_doc_reachability.py``). A hand-kept list decays the same
way the ADR index did twice (``scripts/generate_adr_index.py``); a generated
list checked in ``make validate`` cannot.

What turns ``--check`` red: add, delete or rename a top-level ``docs/*.md``
or a ``docs/<folder>/`` without running this script. Fix:
``python3 scripts/check_docs_map.py``.

What it cannot see: whether the hand-written part names the RIGHT home for a
kind of information, or whether a file inside a folder is worth reading.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / "docs" / "README.md"
BEGIN = "<!-- docs-map:begin (generated by scripts/check_docs_map.py; do not edit by hand) -->"
END = "<!-- docs-map:end -->"

#: A folder's index is the first of these that exists in it. ``docs/adr/`` is
#: the exception: its index is ``docs/24-adr-index.md``, generated and checked
#: by ``scripts/generate_adr_index.py``.
_INDEX_NAMES = ("README.md", "00-index.md", "00-study-index.md", "INDEX.md")
_SPECIAL_INDEX = {
    "adr": "../24-adr-index.md (generated)",
    "analysis": "00-index.md covers the 2026-07 plan only; the rest by date in the file name",
}


def _title(path: Path) -> str:
    """The first ``# `` heading, or the file name when there is none."""
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        match = re.match(r"^#\s+(.+?)\s*$", line)
        if match:
            return match.group(1).replace("|", "\\|")
    return path.name


def _top_level_docs(root: Path) -> list[Path]:
    docs = root / "docs"
    return sorted(p for p in docs.glob("*.md") if p.is_file())


def _folders(root: Path) -> list[Path]:
    docs = root / "docs"
    return sorted(p for p in docs.iterdir() if p.is_dir())


def _folder_index(folder: Path) -> str:
    special = _SPECIAL_INDEX.get(folder.name)
    if special:
        return special
    for name in _INDEX_NAMES:
        if (folder / name).is_file():
            return name
    return "none — read by file name and date"


def render_inventory(root: Path = ROOT) -> str:
    """The generated part, markers included."""
    files = _top_level_docs(root)
    folders = _folders(root)
    lines = [BEGIN, "", "### Every top-level file in `docs/`", ""]
    lines.append("| File | Title |")
    lines.append("|---|---|")
    for path in files:
        lines.append(f"| `{path.name}` | {_title(path)} |")
    lines += ["", "### Every folder in `docs/`", ""]
    lines.append("| Folder | Index |")
    lines.append("|---|---|")
    for folder in folders:
        lines.append(f"| `{folder.name}/` | {_folder_index(folder)} |")
    lines += ["", END]
    return "\n".join(lines) + "\n"


def _split(text: str) -> tuple[str, str, str]:
    """(before, generated, after); raises SystemExit when a marker is missing."""
    start = text.find(BEGIN)
    end = text.find(END)
    if start < 0 or end < 0 or end < start:
        raise SystemExit(
            f"{MAP.relative_to(ROOT)}: the generated section needs both markers, "
            f"{BEGIN!r} then {END!r}"
        )
    end += len(END) + 1  # include the newline after END
    return text[:start], text[start:end], text[end:]


def check(root: Path = ROOT, map_path: Path | None = None) -> int:
    """0 when the map's generated part equals the tree; 1 otherwise."""
    map_path = map_path or (root / "docs" / "README.md")
    if not map_path.is_file():
        print(f"ERROR: {map_path} is missing", file=sys.stderr)
        return 1
    _, current, _ = _split(map_path.read_text(encoding="utf-8"))
    expected = render_inventory(root)
    # Floor: a gate that passes over nothing has measured nothing (AGENTS.md,
    # "Every gate must report what it counted"). A wrong root or a moved docs/
    # directory would otherwise agree trivially with an empty map.
    if len(_top_level_docs(root)) == 0:
        print("ERROR: no top-level docs/*.md found; refusing to pass over nothing", file=sys.stderr)
        return 1
    if current == expected:
        print(
            f"docs map current: {len(_top_level_docs(root))} top-level files, "
            f"{len(_folders(root))} folders listed"
        )
        return 0
    print(
        "ERROR: docs/README.md's generated inventory is stale. Diff (map -> tree):", file=sys.stderr
    )
    for line in difflib.unified_diff(
        current.splitlines(), expected.splitlines(), "docs/README.md", "tree", lineterm=""
    ):
        print(line, file=sys.stderr)
    print("Fix: python3 scripts/check_docs_map.py", file=sys.stderr)
    return 1


def write(root: Path = ROOT, map_path: Path | None = None) -> int:
    map_path = map_path or (root / "docs" / "README.md")
    before, _, after = _split(map_path.read_text(encoding="utf-8"))
    map_path.write_text(before + render_inventory(root) + after, encoding="utf-8")
    print(f"wrote the generated inventory into {map_path.relative_to(root)}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the inventory is stale")
    args = parser.parse_args(argv)
    return check() if args.check else write()


if __name__ == "__main__":
    raise SystemExit(main())
