#!/usr/bin/env python3
"""Print and update the next recommended action for the product factory."""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

spec = importlib.util.spec_from_file_location("skill_router", ROOT / "scripts" / "skill_router.py")
if spec is None or spec.loader is None:
    raise SystemExit("Could not load scripts/skill_router.py")
skill_router = importlib.util.module_from_spec(spec)
spec.loader.exec_module(skill_router)  # type: ignore[union-attr]


def update_console(route: dict[str, object]) -> None:
    reviewers = route.get("reviewers", [])
    blockers = route.get("blocking_gates", [])
    missing = route.get("missing_or_placeholder_evidence", [])
    risks = route.get("risk_triggers_detected", [])
    reviewers_text = "\n".join(f"- `{item}`" for item in reviewers) if reviewers else "- None"
    blockers_text = "\n".join(f"- `{item}`" for item in blockers) if blockers else "- None"
    missing_text = "\n".join(f"- `{item}`" for item in missing) if missing else "- None"
    risks_text = "\n".join(f"- `{item}`" for item in risks) if risks else "- None"
    precedence_text = "\n".join(
        f"{i + 1}. {item}" for i, item in enumerate(route.get("conflict_precedence", []))
    )
    text = f"""# Factory Console

This file is the human-friendly dashboard for the product factory. It is generated by
`make next` and should also be updated by Codex after major steps.

## Current phase

{route.get("label")}

## Next best action

Use driver skill `{route.get("driver")}` to complete the missing/placeholder evidence
listed below. Reviewer skills must review, not overwrite, the driver output.

## Recommended driver skill

`{route.get("driver")}`

## Required reviewer skills

{reviewers_text}

## Blocking gates

{blockers_text}

## Missing or placeholder evidence

{missing_text}

## Risk triggers detected

{risks_text}

## Suggested Codex prompt

```text
{route.get("prompt")}
```

## Conflict precedence

{precedence_text}

## Suggestions dropped by the factory

- Keep the next deliverable to one user, one workflow, one measurable outcome, and one
  vertical slice.
- Ask only blocking questions first; non-blocking unknowns become assumptions or later
  open questions.
- One skill drives an artifact; other skills review it.
- Security, privacy, compliance, AI safety, and source-of-truth gates beat convenience and speed.
- Do not create implementation code until the problem statement, requirements,
  acceptance criteria, architecture, test strategy, and security checks exist.
- Do not claim Jira/Confluence changes were made unless an authorized Atlassian MCP/API
  tool actually made them.
- External skills are reviewer/advisor inputs only until audited and approved.
- Before creating a new local skill, search existing skills first through `make skill-discover`.
- Register and audit future skills through `configs/external-skill-registry.json` and
  `make skill-onboarding-check`.
- Use `make handoff` before closing a Codex session or switching terminals.
- After each major phase, run `make validate`.
- Before release readiness, run `FACTORY_STRICT=1 make validate-strict`.
- Publish study artifacts only after the MVP and most valued outcome are clear.
- Git is the source for study modules; Confluence mirrors them after explicit confirmation.
- Every public artifact must explain AI value, work-easing, security, scalability, and
  enterprise readiness with evidence.
- Diagrams, GIFs, videos, FAQ, technical articles, and LinkedIn posts must pass
  media/publication review before publishing.
"""
    (ROOT / "docs" / "00-factory-console.md").write_text(text, encoding="utf-8")


def main() -> int:
    route = skill_router.route()
    update_console(route)
    print(skill_router.format_route(route))
    print("Updated docs/00-factory-console.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
